spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  data:
    redis:
      password: ""
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/impostor
    username: ${db.username}
    password: ${db.password}

cloud:
  aws:
    s3:
      bucket: ${AWS_S3_BUCKET}
      region: ${AWS_S3_REGION}
    credentials:
      secretKey: ${AWS_S3_SECRET_KEY}
      accessKey: ${AWS_S3_ACCESS_KEY}
    stack:
      auto: false