server:
  port: 8081


management:
  endpoint:
    beans:
      enabled: true  # 특정 엔드포인트 활성화
  endpoints:
    web:
      exposure:
        include: beans  # beans 엔드포인트를 공개

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/impostor
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD} # 본인 비밀번호로 변경
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

  session:
    redis:
      flush-mode: on_save
  data:
    redis:
      host: 127.0.0.1
      password: ""
      port: 6379

cloud:
  aws:
    s3:
      bucket: ${AWS_S3_BUCKET}
      region: ${AWS_S3_REGION}
    credentials:
      secretKey: ${AWS_S3_SECRET_KEY}
      accessKey: ${AWS_S3_ACCESS_KEY}
    stack:
      auto: false
