spring:
  profiles:
    active: core-prod
    include:
      - domain
      - common
management:
  endpoint:
    beans:
      enabled: true  # 특정 엔드포인트 활성화
  endpoints:
    web:
      exposure:
        include: beans  # beans 엔드포인트를 공개
server:
  port: 8081