name: CI/CD 워크플로우

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed
    branches:
      - main


jobs:
  cd:
    runs-on: ubuntu-latest
    env:
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
      AWS_S3_REGION: ${{ secrets.AWS_S3_REGION }}
      AWS_S3_SECRET_KEY: ${{ secrets.AWS_S3_SECRET_KEY }}
      AWS_S3_ACCESS_KEY: ${{ secrets.AWS_S3_ACCESS_KEY }}
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: JDK 17 설치
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Gradle Wrapper 실행 권한 부여
      run: chmod +x ./gradlew
    - name: Gradle Wrapper로 빌드하기
      run: ./gradlew build
    - name: Gradle Wrapper로 테스트 수행
      run: ./gradlew test
